### ISSUE TITLE
Support for Primitive (simple) types in Definitions in Swagger Doc

### ISSUE THREAD

**Issue by kahlil29** [byteally/webapi#14]
The code is written in such a way that we expect the definitions of data in the Definitions HashMap to be complex Arrays/Objects. 
Consider the following Definition entry in the swagger Doc : 
```
  CustomRoleKeyOrId:
    description: The 20-hexdigit id or the key for a custom role.
    example: revenue-team
    type: string
``` 

For this we should probably create a type alias 
`type CustomRoleKeyOrId = Text`
