### ISSUE TITLE
Webapi-Swagger : Handle cases where Swagger Doc has conflicting type and format options.

### ISSUE THREAD

**Issue by kahlil29** [byteally/webapi#9]
Example snippet of Swagger Yaml : 

```
      lastPing:
        example: '2015-03-03T02:37:22.492Z'
        format: int64
        type: string
```

In this case we would probably need to ask for user-input or ask the user to override the type info for this particular property via the config file.
